services:
  - type: web
    name: spark-frontend
    runtime: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sparkbackend-h2g7.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: spark-backend
    env: docker
    plan: free
    buildCommand: cd Backend && dotnet publish -c Release -o ./publish
    startCommand: cd Backend && dotnet ./publish/Backend.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
