services:
  - type: web
    name: spark-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/data/app.db
      - key: Jwt__Key
        value: SparkFinance2024_SecretKey_MustBeLongAndSecure!
      - key: Jwt__Issuer
        value: https://sparkbackend-h2g7.onrender.com
      - key: Jwt__Audience
        value: https://sparkfinance.onrender.com
      - key: Frontend__Url
        value: https://sparkfinance.onrender.com
    healthCheckPath: /api/auth/register
    autoDeploy: true

  - type: web
    name: spark-frontend
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sparkbackend-h2g7.onrender.com
    routes:
      - type: rewrite
        path: /*
        destination: /index.html
