app = "massive-project"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"
  DOTNET_RUNNING_IN_CONTAINER = "true"
  ASPNETCORE_ENVIRONMENT = "Production"
  ConnectionStrings__DefaultConnection = "Data Source=/app/data/app.db"
  Jwt__Key = "YourSuperSecretKeyHere12345678901234567890"
  Jwt__Issuer = "spark-finance"
  Jwt__Audience = "spark-finance-client"
  Frontend__Url = "https://spark-woug4iki9-agbabinas-projects.vercel.app"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "massive_project_data"
  destination = "/app/data"
